all:
	cd Caravel && make clean && make
	cd Client_cpp && make clean && make
	cd Proxy && make clean && make

clean:
	cd Caravel && make clean
	cd Client_cpp && make clean
	cd Proxy && make clean

client:
	cd Client_cpp && ./Client_cpp

proxy:
	cd Proxy && ./Proxy

