all:
	cd Caravel && make clean && make
	cd Client && make clean && make
	cd Proxy && make clean && make

clean:
	cd Caravel && make clean
	cd Client && make clean
	cd Proxy && make clean

client:
	cd Client && ./Client_cpp

proxy:
	cd Proxy && ./TProxy

